spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seminar_management_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Other development-specific configurations...